apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  labels:
    app: gitops-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: gitops-demo-app
          image: ghcr.io/shahzain-khan450/gitops-demo-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: gitops-demo-app-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
